name: Check testcases and quality gate status
 
on:
  pull_request:
    branches:
      - "*"
 
jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
 
      - name: Set branch name
        id: set_branch
        run: |
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
          BRANCH_NM=${{ github.event.number }}
          else
          BRANCH_NM=$(echo ${GITHUB_REF#refs/heads/})
          fi
          echo "BRANCH_NAME=((${BRANCH_NE}))" >> ${{ github.event.number }}
      - name: Scanning the project with sonarQube scanner
        run: |
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            BRANCH_NAME=${{ github.event.number }}
          else
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          fi
            echo "BRANCH_NAME=${BRANCH_NAME}" >> ${{ github.event.number }}
          npm install -g sonarqube-scanner
            sonar-scanner \
              -Dsonar.host.url='http://sonarqube.kcspl.in:9000/' \
              -Dsonar.projectKey='kcs-arpitdixit_branchname' \
              -Dsonar.login=cab872eb9f133e53532de29a9fb7bec0cd9b61e2 \
              -Dsonar.branch.name=$BRANCH_NAME
              -Dsonar.pullrequest.key=${{ github.event.number }}
              -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
              -Dsonar.pullrequest.base=${{ github.BASE_REF }}
 
      - name: identify SonarQube Quality Gate status
        id: quality_gate_status
        run: |
          echo "Identifying quality gate status..."
          STATUS=$(curl -s "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=kcs-arpitdixit_branchname&pullRequest=${{ github.event.number }}" -u "89f09c21d9b7f2f8e67b98200b5772794b4c2872" | jq -r '.projectStatus.status')
          echo "Quality Gate Status : $STATUS"
          
      - name: Check Quality Gate status
        run: |
          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
            echo "SonarQube Quality Gate Failed for branch $BRANCH_NAME!!"
            exit 1
          else
            echo "SonarQube Quality Gate passed for branch $BRANCH_NAME!!"
          fi
